site_name: PymoniK
nav: 
  - Home: index.md
  - Getting Started: getting-started.md
  - FAQ: important-considerations.md
  - Development:
      - Developer's Guide: development/development.md
      - Contributing: development/contribution.md
  - Examples: 
      - Pi Estimation: examples/monte_carlo.md
      - Training an AI to play Pong: examples/pong_training.md
repo_url: https://github.com/aneoconsulting/PymoniK
repo_name: aneoconsulting/PymoniK
site_url: https://aneoconsulting.github.io/PymoniK/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      title: On this page
plugins:
  - social:
      cards_layout: default/invert
extra:
  homepage: https://www.aneo.eu/
theme:
  name: material
  logo: assets/logo-aneo.svg
  features:
    - content.code.copy
    - content.code.annotate 
    - content.tooltips
  palette:
    primary: white
    accent: orange
