[project]
name = "pymonik-worker"
version = "0.1.0"
description = "Worker for PymoniK"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "pymonik",
]

[tool.uv.sources]
pymonik = { path = "../pymonik" }
