name: Publish Docker images

on:
    release:
        types: ["published"]
    workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix: 
        python_version: [3.10.12, 3.11, 3.12]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3            

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: pymonik_worker/Dockerfile
          push: true
          build-args: "USE_PYTHON_VERSION=${{ matrix.python_version }}"
          tags: |
            dockerhubaneo/harmonic_snake:python-${{ matrix.python_version }}-${{ github.ref_name }}
            dockerhubaneo/harmonic_snake:python-${{ matrix.python_version }}
