name: "Publish PymoniK package to PyPI"

on:
  release:
    types: ["published"]

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.10.12  # 
        working-directory: pymonik

      - name: Build
        run: uv build
        working-directory: pymonik

      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
        working-directory: pymonik
